user:
  info:
    url: http://localhost:6443/apiService/
delegate:
  headers: Content-Type,Accept-Language,Cookie

server:
  port: 8085
  servlet:
    context-path: /api

retrofit:
  # 重试配置
  retry:
    # 是否启用全局重试
    enable-global-retry: true
    # 全局重试间隔时间
    global-interval-ms: 100
    # 全局最大重试次数
    global-max-retries: 1
    # 全局重试规则
    global-retry-rules:
      - response_status_not_2xx

  # 熔断降级配置
  degrade:
    # 是否启用全局熔断降级
    enable: true
    # 熔断降级实现方式
    degrade-type: sentinel

  # 连接池配置
  pool:
    # 连接池配置
    userInfo:
      # 最大空闲连接数
      max-idle-connections: 3
      # 连接保活时间(秒)
      keep-alive-second: 100

